apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-deployment
  labels:
    app: spring-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
        - name: spring-hello
          image: spring-hello:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
